### PR TITLE
Add friendly URL slugs

### LINKED ISSUE #11: Pretty URLs which work with human-friendly strings
Currently the word "Affe" is accessible via the URL https://wort.schule/nouns/19 which is not very human friendly. It would be nicer to have it accessible via the URL https://wort.schule/affe. Easier for humans and SEO would benefit too. Obviously it should work with all word types not just with nouns.
 
- [x] We still have to be able to access stuff like the admin page or the impressum. Maybe we should create a save path /intern for those. That would mean that impressum moves to /intern/impressum and admin to /intern/admin, etc.
- [x] Sometimes a word has multiple entries (e.g. "Bauer" https://wort.schule/?filterrific%5Bfilter_wordcontains%5D=Bauer). For those we have to add some sort of additional sequence. That "sequence" should be human readable and child friendly. Not a generic UUID. Adding the Thema could be a potential solution. Or an integer number sequence.
- [x] The link https://wort.schule/nouns/19 should not be used in the application any more if possible. It should always be https://wort.schule/affe
- [x] Add these paths to the robots.txt to not be crawl able by search engines:
  - https://wort.schule/nouns/
  - https://wort.schule/verbs/
  - https://wort.schule/adjectives/

I guess https://github.com/norman/friendly_id is a good gem for this but I am open for all good solutions.

### PR DESCRIPTION
**Pull request by phylor**
Closes #11.

## Changes

* Adds friendly slugs to nouns, verbs and adjectives
* Push footer to bottom of the page, even if the content is not large enough to fill the whole page
* Change from MTI to STI

### CODE REVIEW

**Review by wintermeyer — CHANGES_REQUESTED** [review]
I am not a big fan of putting 887e3892dfeb41d3e50b34e4b95849142b086ed4 into this PR. But no need to remove it now either. 

Otherwise I like the PR. As always well written code.

There is one thing I'd like to change and the current implementation is my bad. I don't think that the URL http://localhost:3000/bauer-spielen-drinnen-teekesselchen works. It is too long. So let's change that and go with http://localhost:3000/bauer-2 which is not ideally either but at least shorter.

If it is not too much work I'd like you to add one more feature: Make the slug on an existing word edible with a validation. The first version (the initial `new` or `create`) should not be edible for a human. It should be generated by `friendly_id`. But after that the `edit` form should have one field for that attribute and run validations on it (e.g. lower case and unique). By that we can "improve" the slug when needed.

**Review by wintermeyer — COMMENTED** [review]
I wasn't able to run a rollback on the migration. Is this a bug or by intention?

```
rails db:rollback
** Invoke db:rollback (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:rollback
== 20221104110839 ChangeMtiToSti: reverting ===================================
-- change_column_null(:words, :type, false)
   -> 0.0010s
-- remove_column(:words, :actable_type, :string)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column "actable_type" of relation "words" does not exist
/Users/stefan/Development/GitHub/wort-schule/wort.schule/db/migrate/20221104110839_change_mti_to_sti.rb:168:in `block in change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "actable_type" of relation "words" does not exist
/Users/stefan/Development/GitHub/wort-schule/wort.schule/db/migrate/20221104110839_change_mti_to_sti.rb:168:in `block in change'

Caused by:
PG::UndefinedColumn: ERROR:  column "actable_type" of relation "words" does not exist
/Users/stefan/Development/GitHub/wort-schule/wort.schule/db/migrate/20221104110839_change_mti_to_sti.rb:168:in `block in change'
Tasks: TOP => db:rollback
(See full trace by running task with --trace)
```

**Comment by phylor** [comment]
> I wasn't able to run a rollback on the migration. Is this a bug or by intention?

This is by intention. The scope of the PR became much bigger than the original task, so I didn't implement the rollback. It would require much more work and a rollback is usually unlikely.

**Comment by phylor** [comment]
@wintermeyer This PR is done from my point of view:

* I removed the topics from the URL in 57f49953657189b683dd01ba066efe1af9f910f8. They are now always sequential if necessary.
* The migration is not able to rollback "by design". Let me know if there is a strong need to roll it back.
* Editable `friendly_id` will be added in a new PR, if that's okay.

**Review by wintermeyer — APPROVED** [review]

**Pull request merged**
