### PR TITLE
Feature #120: Word Index for SEO

### PR DESCRIPTION
**Pull request by phortx**
See #120 

This is the minimal version. Please tell me when you need any further improvements, optimizations or features.

I had some trouble with testing due to the lack of a complete dataset and only having the minimal seed data. Maybe one of you guys have a copy of the production data on localhost and can check if everything works correctly.

### CODE REVIEW

**Review by phylor — CHANGES_REQUESTED** [review]
I would work on two things:

* I'd appreciate a test showing the index with fully filled words of all word types, because the view currently throws errors for all word types.
* The design is not consistent with the rest of the app yet and needs a bit of cleanup.

**Comment by wintermeyer** [comment]
> * I'd appreciate a test showing the index with fully filled words of all word types, because the view currently throws errors for all word types.

That was my bad. I asked @phortx for a quick and dirty solution. But for future developers - not having proper tests here - might become a trap.

@phortx please send me an email with an offer for better/proper testing.

> * The design is not consistent with the rest of the app yet and needs a bit of cleanup.

@phylor I see your point but I am fine with that for now. Right now this is mainly for SEO. Once we have finished the search we can revisit this and update the design.

**Comment by phortx** [comment]
> > * I'd appreciate a test showing the index with fully filled words of all word types, because the view currently throws errors for all word types.
> 
> That was my bad. I asked @phortx for a quick and dirty solution. But for future developers - not having proper tests here - might become a trap.
> 
> @phortx please send me an email with an offer for better/proper testing.

Offer sent and ordere. I'll write the tests :) 

> > * The design is not consistent with the rest of the app yet and needs a bit of cleanup.
> 
> @phylor I see your point but I am fine with that for now. Right now this is mainly for SEO. Once we have finished the search we can revisit this and update the design.

I copied the design from the imprint page.

**Comment by phortx** [comment]
@phylor do you have a database dump with more words then the seed? That would help me a lot :)

**Comment by phortx** [comment]
I implemented all the feedback. Next step is to write the tests.

**Comment by phortx** [comment]
Also I added a simple, pragmatic test

**Review by phylor — APPROVED** [review]
@phortx Looks great, thank you! :tada:

**Comment by phortx** [comment]
> @phortx Looks great, thank you! 🎉

Nice! Thank you very much :)

**Pull request merged**
